baseURL = 'https://JunNishimura.github.io/chatify-site/'
languageCode = 'en-us'
defaultcontentlanguage = "en"
title = 'Chatify'
theme = 'hugo-coder'
publishDir = "docs"

[markup.highlight]
style = "github-dark"

[params]
  author = "Chatify"
  info = "Chat based music recommendation app"
  description = "chatify's website"
  keywords = "AI, music, recommendation"
  avatarurl = "images/chatify.png"

  faviconSVG = "images/favicon.svg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

[[menu.main]]
  name = "Policy"
  weight = 1
  url = "policy/main/"

[[menu.main]]
  name = "Manual"
  weight = 1
  url = "manual/main/"